print("     *****")
print("    *******")
print("   *********")
print("  ****( )****")
print("   *********")
print("    *******")
print("     *****")
print("      | |  ")
print("  __  | |  __")
print("  \ \ | | / /")
print("   \ \| |/ /")
print("    \ | | /  ")
print("     /   \   ")
print("\|/_/_____\_\|/")
