names = ['Sam', 'Gianna', 'Emily', 'Jacob', 'Holden', 'Maverick', 'Nicky', 'Ian', 'Ryan']
print("These are my friends:")
print(names[0])
print(names[2])
print(names[3])
print(names[5])
print(names[6])
print(names[7])
print(names[8])
print("I dont really know this person:")
print(names[4])
print("I CAN NOT STAND THIS PERSON!:")
print(names[3])