print("This is a madlib! Fill in the following words to create it.")
name1 = input("Write the first name to apear in the story: ")
name2 = input("Write the second name to apear in the story: ")
noun1 = input("Write the first noun to apear in the story: ")
noun2 = input("Write the second noun to apear in the story: ")
noun3 = input("Write the third noun to apear in the story: ")
noun4 = input("Write the fourth noun to apear in the story. Make sure it is plural: ")
noun5 = input("Write the fith noun to apear in the story: ")
adj1 = input("Write the first adjative to apear in the story: ")
adj2 = input("Write the second adjative to apear in the story: ")
adj3 = input("Write the third adjative to apear in the story: ")
adj4 = input("Write the fourth adjative to apear in the story: ")
adj5 = input("Write the fith adjative to apear in the story: ")
adj6 = input("Write the sixth adjative to apear in the story: ")
verb1 = input("Write the first past tense verb to apear in the story: ")
verb2 = input("Write the second past tense verb to apear in the story: ")
print(" ")
print("I am a very ", adj1, " ", noun1, " named ", name1, ", and I'm super ", adj2, ".")
print("I once ", verb1, " on over to the ", noun2, " and ", verb2, " some ", adj4, " ", noun3, ".")
print("She was ", adj5, " and called ", name2, ".")
print("I have ", adj6, " ", noun4, " about her at ", noun5, ".")