print("This will predict what year it will be when you are a certain age.")
start = input("When were you born? ")
age = input("What age do you want to predict? ")
end = int(start) + int(age)
print("The year will be:", end)